### ISSUE TITLE
Products app hangs on rendering products list, when run without signin app in Firefox

### ISSUE THREAD

**Issue by tomalec** [StarcounterSamples/Products#30] opened 2016-09-02 11:27 UTC
### Steps to reproduce the behaviour
1. Run Launcher and Products app
2. Open the Firefox with http://localhost:8080/launcher
3. Click on "Products" icon

### Expected behaviour

Product list partial should render

### Actual behaviour

Blank screen is show, console is full of parsing errors 

### Technical information

Probably, it happens because it tries to parse standalone page as a Document Fragment to be put into Shadow DOM, which may cause an infinite loop.

It was introduced after https://github.com/StarcounterPrefabs/Launcher/commit/39da52caab8b6f9275d05d97d0e4cac6794d71d0

##### Starcounter version
2.2.1.3018

##### Involved apps' version
- StarcounterPrefabs/Launcher@05efc44175
- StarcounterSamples/Products@0bda5da3c0

### Screenshot

![image](https://cloud.githubusercontent.com/assets/17435/18202538/e366a8f8-7110-11e6-8ea6-f5b79e39c51e.png)

**Comment by tomalec** [comment] 2016-09-02 11:55
It works fine with StarcounterPrefabs/Launcher@050eb2b7beb00472cfc72b938b6c6846bd7a9429
So, it seems it was introduced in 
https://github.com/StarcounterPrefabs/Launcher/commit/39da52caab8b6f9275d05d97d0e4cac6794d71d0

**Comment by warpech** [comment] 2016-09-02 13:01
So the problem is that Products app uses the existence of `Session` to detect if Launcher is running.

If it thinks that Launcher is not running, it returns the full Standalone page, which creates PuppetJs, causing the infinite loop.

Products app needs to be change to detect Launcher by some different means.

I will fix that.

**Comment by warpech** [comment] 2016-09-02 16:55
Solved in #31. @diliger pls review.

**Comment by warpech** [comment] 2016-09-16 08:53
Fixed in #31

**Closed by warpech** 2016-09-16 08:53 UTC
