### ISSUE TITLE
Barcode field loses focus after each keypress in non-Chrome browsers

### ISSUE THREAD

**Issue by miyconst** [StarcounterSamples/Products#8] opened 2016-02-25 15:32 UTC
This might be something with the new SysUpgrade.

cc @warpech

**Comment by warpech** [comment] 2016-02-25 16:38
Bug confirmed in FF, Safari, Edge, IE with SysUpgrade.

Works good in Chrome.

This might be connected with the Barcode field listening on `::input` event. But there is also an `::input` field in KitchenSink and that one works fine... 

I don't have any immediate idea what might be the reason. Do you have any ideas about it?

**Comment by warpech** [comment] 2016-02-25 17:20
Note to self: The bug happens only with Launcher's `starcounter-include`, not with original `starcounter-include`.

It also doesn't happen if I replace this line in Launcher's `starcounter-include`:

```html
<link rel="import" href="../juicy-tile-table/juicy-tile-table.html">
```

With:

```html
<!--<link rel="import" href="../juicy-tile-table/juicy-tile-table.html">-->
```

(disabling j-t-t/j-t-l)

**Comment by warpech** [comment] 2016-02-26 08:13
The problem is connected to how I am notifying Polymer 1.2 & 1.3 to refresh bound elements.

My solution to refreshing `dom-bind`'s (a little bit described here https://github.com/StarcounterSamples/SysUpgrade/issues/2) works by omitting  Polymer's public `notifyPath` method by calling the "private" `_pathEffector` method. 

This bypasses the Polymer's check if a new value is different from the previous value. It has 2 consequences:

- positive: nested elements are notified when object properties change, even if the object is the same
- negative: it reassigns the property, which causes redundant work in elements which don't have a check for that. Specifically, Launcher's `starcounter-include` detects this as reload of the partial. 

As a workaround, the following check must to be added to Launcher's `starcounter-include`:

```js
Object.defineProperty(this,"partial",{
        set: function(newValue){
            if (partial !== newValue) { //ADD THIS CHECK
                partial = newValue;
                starcounterInclude.partialChanged(partial);
            }
        },
        get: function(){
          return partial;
        }
      });
```

@miyconst, @tomalec - any comments?

**Comment by miyconst** [comment] 2016-02-26 10:09
The fix looks good to me.

**Comment by tomalec** [comment] 2016-02-26 10:52
In general I'm afraid that we are making snowball of workarounds, and it may hit us later even more.

Obviously if it works, it's better to keep it at least until Polymer will refactor templating engine, and few polyfill fixes will be done correctly.

Make we could somehow reduce the range of templates being notified at 
https://github.com/StarcounterSamples/SysUpgrade/blob/master/SysUpgrade/wwwroot/sys/puppet-client/puppet-client.html#L232 ?

**Comment by warpech** [comment] 2016-02-26 11:31
> Make we could somehow reduce the range of templates being notified at 
https://github.com/StarcounterSamples/SysUpgrade/blob/master/SysUpgrade/wwwroot/sys/puppet-client/puppet-client.html#L232 ?

Potentially I can try to notify all the relevant `templates` in https://github.com/StarcounterSamples/SysUpgrade/blob/master/SysUpgrade/wwwroot/sys/puppet-client/puppet-client.html#L298. This will require a lot of checking for model scopes, but in turn make `_objChanged` not needed anymore. 

But I don't know if this would work for other vanilla CE that use object properties in their configuration. How else can I notify the CE that a property object has changed, if not by reassigning it?

**Comment by tomalec** [comment] 2016-02-26 13:30
Well I would say that for vanilla CE you should only change the object. Then it's up to the CE how it observes the changes (setter/attributeChangedCallback/O.o)

**Comment by warpech** [comment] 2016-02-26 16:24
Problem fixed. The discussed changes to `_objChanged` are tracked in a new issue: https://github.com/PuppetJs/puppet-polymer-client/issues/1

**Closed by warpech** 2016-02-26 16:24 UTC
Labels: bug
